// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriMatch.Data;
#nullable disable
namespace NutriMatch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610143316_AddRecipeIngredients")]
    partial class AddRecipeIngredients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("NutriMatch.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<float>("Rating")
                        .HasColumnType("real");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Recipes");
                });
            modelBuilder.Entity("NutriMatch.Models.RecipeIngredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<float>("Quantity")
                        .HasColumnType("real");
                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");
                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("RecipeId");
                    b.ToTable("RecipeIngredients");
                });
            modelBuilder.Entity("NutriMatch.Models.RecipeIngredients", b =>
                {
                    b.HasOne("NutriMatch.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");
                });
            modelBuilder.Entity("NutriMatch.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
